services:
  db:
    image: postgres:latest
    container_name: db-container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: integration_dev
    ports:
      - "4321:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend-container
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: integration_dev
      PORT: 4001
    ports:
      - "4001:4001"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - app-network
    command: ["sh", "-c", "npm install && npm run dev"]

  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    ports:
      - "4000:4000"
    volumes:
      - ./frontend:/app
    networks:
      - app-network
    depends_on:
      - backend
    command: npm run start

networks:
  app-network:
    driver: bridge

volumes:
  pg_data:
